# Generated by Django 3.2.3 on 2021-05-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registo_hora_extra', '0003_registohoraextra_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registohoraextra',
            name='horas',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
